# Generated by Django 4.2.5 on 2023-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_location_id_alter_search_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
