# Generated by Django 4.2.5 on 2023-09-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_search_latitude_search_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='search',
            name='longitude',
        ),
    ]
