# Generated by Django 4.2.5 on 2023-09-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_location_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='ip_address',
            field=models.CharField(max_length=15),
        ),
    ]
